Neopets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django import views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('neopets/', views.neopets_index, name='index'),
    path('neopets/<int:neopet_id>/', views.neopets_detail, name='detail'),
    path('neopets/create/', views.NeopetCreate.as_view(), name='neopets_create'),
    path('neopets/<int:pk>/update/', views.NeopetUpdate.as_view(), name='neopets_update'),
    path('neopets/<int:pk>/delete/', views.NeopetDelete.as_view(), name='neopets_delete'),
    path('neopets/<int:neopet_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('neopets/<int:neopet_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.toys_index, name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

class Toy(models.Model):
    name = models.CharField(max_length=25)
    color = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})
    
    def __str__(self):
        return self.name


class Neopet(models.Model):
    name = models.CharField(max_length=30)
    species = models.CharField(max_length = 20)
    gender = models.CharField(max_length=20)
    temperament = models.CharField(max_length=30)
    # M:M
    toys = models.ManyToManyField(Toy)
    # 1:M for user
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'neopet_id': self.id})

class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    # neopet_id FK
    neopet = models.ForeignKey(Neopet, on_delete=models.CASCADE)
    
    

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Neopet, Toy
from .forms import FeedingForm

# Create your views here.

def home(request):
    return render(request, "home.html")

def about(request):
    return render(request,"about.html")

# neopets #

def neopets_index(request):
    neopets = Neopet.objects.filter(user=request.user)
    return render(request, 'neopets/index.html', {'neopets': neopets })


@login_required
def neopets_detail(request, neopet_id):
    neopet = Neopet.objects.get(id=neopet_id)
    feeding_form = FeedingForm()
    # displaying unassociated toys
    toys_neopet_doesnt_have = Toy.objects.exclude(id__in = neopet.toys.all().values_list('id'))
    return render(request, 'neopets/detail.html', {
    # include the cat and feeding_form in the context
    'neopet': neopet,
    'feeding_form': feeding_form,
    'toys' : toys_neopet_doesnt_have,
  })

@login_required
def add_feeding(request, neopet_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.neopet_id = neopet_id
        new_feeding.save()
    return redirect('detail', neopet_id=neopet_id)

@login_required
def assoc_toy(request, neopet_id, toy_id):
  # Note that you can pass a toy's id instead of the whole object
   Neopet.objects.get(id=neopet_id).toys.add(toy_id)
   return redirect('detail', neopet_id=neopet_id)
# toys #

# CBV's
class NeopetCreate(LoginRequiredMixin,CreateView):
    model = Neopet
    fields = ['name', 'species', 'temperament', 'gender']
    # success_url= '/neopets/'
    def form_valid(self, form):
    # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the neopet
    # Let the CreateView do its job as usual
        return super().form_valid(form)


class NeopetUpdate(LoginRequiredMixin,UpdateView):
    model = Neopet
    fields = ['species', 'temperament', 'gender']

class NeopetDelete(LoginRequiredMixin,DeleteView):
    model = Neopet
    success_url = '/neopets/'

# Toys #
class ToyCreate(LoginRequiredMixin,CreateView):
    model = Toy
    fields = ('name', 'color')
    def form_valid(self, form):
    # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the toy
    # Let the CreateView do its job as usual
        return super().form_valid(form)

class ToyUpdate(LoginRequiredMixin,UpdateView):
    model = Toy
    fields = ('name', 'color')

class ToyDelete(LoginRequiredMixin,DeleteView):
    model = Toy
    success_url = '/toys/'

class ToyDetail(LoginRequiredMixin,DetailView):
    model = Toy
    template_name = 'toys/detail.html'

# class ToyList(LoginRequiredMixin,ListView):
#     model = Toy
#     template_name = 'toys/index.html'
    
def toys_index(request):
    toys = Toy.objects.filter(user=request.user)
    return render(request, 'toys/index.html', {'toys': toys })



#################################################################
# Signup code, just google or look at md for reference
def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}{% block content %}
<div class="container">
    <div class="about">
        <h1>About Neopets</h1>
        <hr />
        <p class="flow-text">
            <strong>
            <p>Hello and welcome! Neopets is a small mock-up of the original Neopets site, where their users can own a neopet and feed them, play with them, accessorize them, play games together and more!</p>
            <p>Feel free to make an account so you can get started with adopting your neopets, feeding them meals, and giving them toys so they can be entertained.</p>
            <p>There are many neopets to be collected, so in the near future users can expect the addition of a third party API containing all possible neopets so that you can adopt them with their preloaded images!</p>
            <p>Thanks for stopping by! Feel free to check out the real site at neopets.com</p>
            </strong>
        </p>
    </div>
</div>

 {% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Neopets</title>
    <!-- My own materialize -->
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- icon library for links -->
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <!-- link to static css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body class="green lighten-3">
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper #fff9c4 yellow lighten-4">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo black-text" id="neopet-logo">&nbsp;&nbsp;<img src="https://images.neopets.com/themes/h5/basic/images/v3/np-logo-R.svg"></a>
                    </li>
                </ul>
                <ul class="right black-text">
                    <li><a class="black-text" href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="black-text" href="{% url 'toys_create' %}">Add a Toy</a></li>
                    <li><a class="black-text" href="{% url 'toys_index' %}">View All Toys</a></li>
                    <li><a class="black-text" href="{% url 'neopets_create' %}">Add a Neopet</a></li>
                    <li><a class="black-text" href="{% url 'index' %}">View All My Neopets</a></li>
                    <li><a class="black-text" href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a class="black-text" href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a class="black-text" href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
            </span>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer #e3f2fd yellow lighten-4">
        <div class="container">
            <section class="mb-4">
                <!-- Linkedin -->
                <a class="btn btn-primary btn-floating waves-effect waves-light" id="linkedin"
                    href="https://www.linkedin.com/in/brandon-a-hernandez"><i
                        class="fab fa-linkedin-in"></i></a>
                        <!-- try putting image instead i tag for icon, name image class so can css it -->
                <!-- Github -->
                <a class="btn btn-primary btn-floating waves-effect waves-light" id="github"
                    href="https://github.com/brandonhernandez304/neopets_mockup" >
                    <i class="fab fa-github"></i></a>
            </section>
            <div class="right black-text">
                All Rights Reserved, &copy; 2022 Neopets &nbsp;
            </div>

            </section>
        </div>
    </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}{% block content %}

<body id="home">
    
    {% load static %} 
    
    <img src="{% static 'images/neopets.png' %}" class="responsive-img">
</body>

 {% endblock %}

main_app/templates/main_app/neopet_confirm_delete.html
{% extends 'base.html' %}{% block content %}
<h1>Release Neopet</h1>

<h4> Are you sure you want to release
    <span class="name-text">{{ object.name}} </span> into the wilds?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, run free!" class="btn  waves-effect waves-light" />
    <a class="btn orange waves-effect waves-light" href="{% url 'detail' neopet.id %}">Nevermind, I'll miss them!</a>
</form>
{% endblock %}

main_app/templates/main_app/neopet_form.html
{% extends 'base.html' %}{% block content %}
<!-- "" makes form post to same url used to display it -->
{% if object %}
<h1>Edit <span class="name-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add a Neopet</h1>
{% endif %}
<form action="" method="post">
{% csrf_token %}
<table>
    <!-- render the inputs inside tr's and td's -->
    {{ form.as_table }}
</table>
<input type="submit" value="Submit!" class="btn #ffab00 amber accent-4 waves-effect waves-light" />
</form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Toy</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red waves-effect waves-light" type="submit" value="Yes - Delete">
    <a class="btn blue waves-effect waves-light" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Update {{ object.name }}</h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn #ffab00 amber accent-4 waves-effect waves-light" type="submit" value="{% if object %} Update Toy {% else %} Add Toy {% endif %}">
</form>

{% endblock %}

main_app/templates/neopets/detail.html
<!-- ######################################################## -->

{% extends 'base.html' %} {% block content %}

<h1>Neopet Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card #fafafa grey lighten-5 z-depth-5">
            <div class="card-content">
                <span class="card-title">{{ neopet.name }}</span>
                <p> Species: {{ neopet.species }}</p>
                <p> Temperament: {{ neopet.temperament }}</p>
                <p> Gender: {{ neopet.gender }} </p>
            </div>
            <div class="card-action">
                <a href="{% url 'neopets_update' neopet.id %}">Change Some Details</a>
                <a href="{% url 'neopets_delete' neopet.id %}">Set Free!</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' neopet.id %}" method="post">
            {% csrf_token %} {{ feeding_form.as_p }}
            <input type="submit" class="btn #ffab00 amber accent-4 waves-effect waves-light" value="Add Feeding" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in neopet.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr />
<div class="row">

    <div class="col s6">
        <h3>{{ neopet.name }}'s Toys</h3>
        {% if neopet.toys.count %} {% for toy in neopet.toys.all %}
        <div class="card #fafafa grey lighten-5 lighten-5 z-depth-5">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
        </div>
        {% endfor %} {% else %}
        <h5>Give {{ neopet.name }} something to play with!</h5>
        {% endif %}
    </div>


    <!-- Available toys will come after this line -->
    <div class="col s6">
        <h3>Available Toys</h3>
        {% if toys.count %}
        {% for toy in toys.all %}
        <div class="card #fafafa grey lighten-5
        z-depth-5">
            <div class="card-content">
                <span class="card-title">
                    A <span class="{{ toy.color }}-text">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_toy' neopet.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="waves-effect btn #ffab00 amber accent-4 waves-effect waves-light">Give</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{neopet.name}} Already Has All Toys Available</h5>
        {% endif %}
    </div>
</div>

<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    // add additional JS to initialize select below
    var selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/neopets/index.html
{% extends 'base.html' %}{% block content%}

<h1>Neopets List</h1>

{% for neopet in neopets %}

    <div class="card z-depth-5 #ffcc80 orange lighten-3">
        <a class= 'white-text'href="{% url 'detail' neopet.id %}">
            <div class="card-content">
                <span class="card-title"><h2> {{ neopet.name }} </h2></span>
                <p> Species: {{ neopet.species}} </p>
                <p> Gender: {{ neopet.gender }}</p>
                <p> Temperament: {{ neopet.temperament }}</p>
            </div>
        </a>
    </div>
    {% endfor %}{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Toy Details</h1>


<div class="card z-depth-5">
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'toys_update' toy.id %}">Edit</a>
            <a href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Toys List</h1>
{% for toy in toys %}
<div class="card z-depth-5 #ffccbc deep-orange lighten-4">
    <a class="white-text" href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color }}-text"></span> {{ toy.name }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}